name: release

on:
  push:
    tags:
      - '*'
jobs:
  goreleaser:
    runs-on: ubuntu-22.04
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.2'
          cache: true

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3-)

      - name: Get the datetime
        id: get_datetime
        run: echo ::set-output name=DATE_TIME::$(date +%Y-%m-%d)

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
          workdir: go-starknet
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TOKEN: ${{ secrets.HOMEBREW_TOKEN }}
          DATE_TIME: ${{ steps.get_datetime.outputs.DATE_TIME }}
          VERSION: ${{ steps.get_version.outputs.VERSION }}
